dist: trusty
language: node_js
node_js:
- "8"
env:
  global:
    - NODE_ENV=production
before_install:
- cd prereg
install:
- npm install --production
script:
- npm run track;
after_success:
- if [ "$TRAVIS_EVENT_TYPE" == 'cron' ] || [ "$TRAVIS_COMMIT_MESSAGE" == 'run' ]; then
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "DrKelsey";
    git checkout $TRAVIS_BRANCH;
    git add -A && git commit -m "Automated Data Update";
    git push -q https://dragonjet:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG;
  fi
