    {
      icon = "{{icon}}",
      name = "{{name}}",
      type = {{type}},
      description = "{{description}}",
      max_description = "{{max_description}}",
      range = "{{range}}",
      max_range = "{{max_range}}",
      spcost = {{spcost}},
      max_spcost = {{max_spcost}},
      duration = {{duration}},
    },