    {
      icon = "{{icon}}",
      name = "{{name}}",
      recharge = "{{recharge}}",
      trigger = "{{trigger}}",
      passive = {{passive}},
      description = "{{description}}",
      max_description = "{{max_description}}",
      range = {{range}},
      max_range = {{max_range}},
      spcost = {{spcost}},
      max_spcost = {{max_spcost}},
      duration = {{duration}},
    },