    {
      icon = "{{icon}}",
      name = "{{name}}",
      recharge = "{{recharge}}",
      trigger = "{{trigger}}",
      passive = {{passive}},
      description = "{{description}}",
      sp = { {{spcost}} },
      duration = { {{duration}} },
    },